apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.testsuite.service.name }}
spec:
  selector:
    app: {{ .Values.testsuite.name }}
  ports:
    - protocol: TCP
      port: {{ .Values.testsuite.service.port }}
      targetPort: {{ .Values.testsuite.service.port }}
  type: ClusterIP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.testsuite.name }}
  labels:
    app: {{ .Values.testsuite.name }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ .Values.testsuite.name }}
  template:
    metadata:
      name: {{ .Values.testsuite.name }}
      labels:
        app: {{ .Values.testsuite.name }}
    spec:
      containers:
        - name: {{ .Values.testsuite.name }}
          image: loadimpact/k6:latest
          imagePullPolicy: Always
          env:
            - name: HOST
              value: {{ .Values.springDemo.service.name }}
          volumeMounts:
            - mountPath: /scripts
              name: test-volume
          command: [ "k6" ]
          args: [ "run", "/scripts/script.js" ]
      volumes:
        - name: test-volume
          configMap:
            name: {{ .Values.testsuite.configmap.name }}
            items:
              - key: 'environment'
                path: 'environment.js'
              - key: 'script'
                path: 'script.js'
              - key: 'samplesUC'
                path: 'usecases/samplesUC.js'
      restartPolicy: Always

