apiVersion: apps/v1
kind: Deployment
metadata:
  name: k6-testsuite
  labels:
    app: k6-testsuite
spec:
  replicas: 1
  selector:
    matchLabels:
      app: k6-testsuite
  template:
    metadata:
      name: k6-testsuite
      labels:
        app: k6-testsuite
    spec:
      containers:
        - name: k6-testsuite
          image: loadimpact/k6:latest
          imagePullPolicy: Always
          env:
            - name: HOST
              value: spring-demo
          volumeMounts:
            - mountPath: /scripts
              name: test-volume
          command: [ "k6" ]
          args: [ "run", "/scripts/script.js" ]
      volumes:
        - name: test-volume
          configMap:
            name: script-configmap
            items:
              - key: 'environment'
                path: 'environment.js'
              - key: 'script'
                path: 'script.js'
              - key: 'samplesUC'
                path: 'usecases/samplesUC.js'
      restartPolicy: Always

