apiVersion: v1
kind: Pod
metadata:
  name: k6-testsuite
  labels:
    app: k6-testsuite
spec:
  containers:
    - name: k6-testsuite
      image: loadimpact/k6:latest
      imagePullPolicy: Always
      env:
        - name: HOST
          value: spring-demo
      volumeMounts:
        - mountPath: /scripts
          name: test-volume
      command: ['/bin/sh']
      args: ['/scripts/runK6.sh']
  volumes:
    - name: test-volume
      hostPath:
        path: /mnt/c/Users/eegsraz/IdeaProjects/spring-demo-k6/src/test/k6
  restartPolicy: Always
