apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.springDemo.service.name }}
spec:
  selector:
    app: {{ .Values.springDemo.name }}
  ports:
    - protocol: TCP
      port: {{ .Values.springDemo.service.port }}
      targetPort: {{ .Values.springDemo.service.port }}
  type: ClusterIP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.springDemo.name }}
  labels:
    app: {{ .Values.springDemo.name }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ .Values.springDemo.name }}
  template:
    metadata:
      name: {{ .Values.springDemo.name }}
      labels:
        app: {{ .Values.springDemo.name }}
    spec:
      containers:
        - name: {{ .Values.springDemo.name }}
          image: szalaigeri/spring-demo:1.0.0
          imagePullPolicy: Always
      restartPolicy: Always