apiVersion: v1
kind: Service
metadata:
  name: spring-demo
spec:
  selector:
    app: spring-demo
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
  type: ClusterIP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: spring-demo
  labels:
    app: spring-demo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: spring-demo
  template:
    metadata:
      name: spring-demo
      labels:
        app: spring-demo
    spec:
      containers:
        - name: spring-demo
          image: szalaigeri/spring-demo:1.0.0
          imagePullPolicy: IfNotPresent
      restartPolicy: Always